### ISSUE TITLE
Fix: definir linguagem para nomenclatura

### ISSUE THREAD

**Issue by DevdouglasGfs** [bear-system-dev/whyapp-frontend#39]
Definir se inglês ou português será a língua padrão para que padronizemos os nomes das variáveis, propriedades de objetos e demais recursos

**Comment by artenlf** [comment]
Concordo. No Front havíamos definido que seria tudo em inglês, mas a API tem trechos em português. Acredito que seja melhor para este projeto pontualmente, utilizarmos o padrão em PT-BR mesmo.

Na parte de refactor e limpeza do código, será assinalada uma task para essa issue.

Para os próximos projetos fica a lição para definirmos antes com toda a equipe para evitar conflitos.

**Comment by DevdouglasGfs** [comment]
Até uma nova decisão essa issue será mantida fechada.
